name: Run the project's self-tests
on: [push, pull_request]

jobs:
  runtest_task:
    name: Validate TypeScript types
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install NodeJS 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Test types
        run: npm run test-types
