name: voiceover-test
on:
  push:
    branches:
      - voiceover

jobs:
  voiceover-test:
    runs-on: macos-13
    steps:
      # Checkout all repos first (helps cache purposes)
      - uses: actions/checkout@v4

      - name: Review registered components (before fetching release)
        run: |
          /System/Library/Frameworks/CoreServices.framework/Versions/Current/Frameworks/LaunchServices.framework/Versions/Current/Support/lsregister -dump | awk '/^bundle id: *ATDriver/,/^-+$/'

      - uses: robinraju/release-downloader@v1.10
        with:
          repository: 'w3c/aria-at-automation-driver'
          tag: 'v0.0.1-beta'
          extract: true
          out-file-path: aria-at-automation-driver

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Review registered components (before npm install)
        run: |
          /System/Library/Frameworks/CoreServices.framework/Versions/Current/Frameworks/LaunchServices.framework/Versions/Current/Support/lsregister -dump | awk '/^bundle id: *ATDriver/,/^-+$/'

      - name: "automation-driver: npm install"
        working-directory: aria-at-automation-driver/package
        run: npm install

      - name: Review registered components (before binary install)
        run: |
          /System/Library/Frameworks/CoreServices.framework/Versions/Current/Frameworks/LaunchServices.framework/Versions/Current/Support/lsregister -dump | awk '/^bundle id: *ATDriver/,/^-+$/'

      - name: "automation-driver: install"
        env:
          DEBUG: '*'
        working-directory: aria-at-automation-driver/package
        run: ./bin/at-driver install --unattended

      - name: Review registered components (after binary install)
        run: |
          /System/Library/Frameworks/CoreServices.framework/Versions/Current/Frameworks/LaunchServices.framework/Versions/Current/Support/lsregister -dump | awk '/^bundle id: *ATDriver/,/^-+$/'

      - name: Start AT Driver server
        working-directory: aria-at-automation-driver/package
        run: |
          ./bin/at-driver serve 2> output.txt &
          sleep 4
          say Something!
          cat output.txt
          kill %%
