name: voiceover-test
on:
  push:
    branches:
      - voiceover

jobs:
  nvda-test:
    runs-on: macos-13
    steps:
      # Checkout all repos first (helps cache purposes)
      - uses: actions/checkout@v4

      - uses: robinraju/release-downloader@v1.10
        with:
          repository: 'w3c/aria-at-automation-driver'
          tag: 'v0.0.1-beta'
          extract: true
          out-file-path: aria-at-automation-driver

      - name: debug
        working-directory: aria-at-automation-driver/package
        run: ls -lah

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: "automation-driver: npm install"
        working-directory: aria-at-automation-driver/package
        run: npm install

      - name: "automation-driver: install"
        env:
          DEBUG: '*'
        working-directory: aria-at-automation-driver/package
        run: ./bin/at-driver install --unattended
