name: voiceover-test
on:
  push:
    branches:
      - macos-14

env:
  ARIA_AT_WORK_DIR: 'tests/alert'
  ARIA_AT_CALLBACK_URL: 'http://example.com'
  ARIA_AT_STATUS_URL: 'http://example.com'
  ARIA_AT_CALLBACK_HEADER: 'x-header-param:empty'

jobs:
  permissions-14:
    runs-on: macos-14
    steps:
      - name: Check permissions
        run: ls -lahd /usr/local
      - name: Check permissions
        run: ls -lahd /usr/local/var
