name: voiceover-test-debug
on: push

env:
  ARIA_AT_WORK_DIR: 'tests/alert'
  ARIA_AT_CALLBACK_URL: 'http://example.com'
  ARIA_AT_STATUS_URL: 'http://example.com'
  ARIA_AT_CALLBACK_HEADER: 'x-header-param:empty'
  BROWSER: 'safari'
  AT_DRIVER_SERVER_VERSION: '~0.0.6'

jobs:
  voiceover-test:
    runs-on: macos-15
    steps:
      # Checkout all repos first (helps cache purposes)
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install the macOS AT Driver server package
        run: npm install @bocoup/macos-at-driver-server@"${AT_DRIVER_SERVER_VERSION}"

      - name: Configure the system to support the AT Driver server
        env:
          DEBUG: "*"
        run: ./install-for-macos.sh
